resources:
- minio.yaml
- namespace.yaml

helmCharts:
  - name: zot
    releaseName: zot
    repo: https://zotregistry.dev/helm-charts
    namespace: zot
    version: 4.10.0
    includeCRDs: true
    valuesInline:
      replicaCount: 2
      ingress:
        enabled: true
        annotations: 
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        # If using nginx, disable body limits and increase read and write timeouts
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
        className: "nginx"
        pathtype: ImplementationSpecific
        hosts:
          - host: zot.bandit.shutthegoatup.com
            paths:
              - path: /
      httpGet:
        scheme: HTTPS

      persistence: false
      # PVC data, only used if persistence is 'true'
      pvc:
        # Make the chart create the PVC, this option is used with storageClasses that
        # can create volumes dynamically, if that is not the case is better to do it
        # manually and set create to false
        create: true
        # Name of the PVC to use or create if persistence is enabled, if not set the
        # value '$CHART_RELEASE-pvc' is used
        name: null
        # Volume access mode, if using more than one replica we need
        accessMode: "ReadWriteOnce"
        # Size of the volume requested
        storage: 500Gi
        # Name of the storage class to use if it is different than the default one
        storageClassName: openebs-zfspv