resources:
  - ../../../bases/config
  - ../../../bases/httpbin
  - ../../../bases/openebs
  - ../../../bases/zitadel
  - ../../../bases/mailhog


components:
  - ../../../components/replace-server-name