apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.1
    namespace: cert-manager
    includeCRDs: false
