---   
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-eu-central-1
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store-eu-central-1
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-central-1
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager-eu-west-2
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameter-store-eu-west-2
spec:
  provider:
    aws:
      service: ParameterStore
      region: eu-west-2
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: robot
          audience: kubernetes
      server: http://vault.vault.svc.cluster.local:8200
      version: v2
