name: 'Kube Login'
description: 'Places .kube/config file with GHA id_token'
inputs:
  cluster:  # id of input
    description: 'kubectx name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install OIDC Client from Core Package
      shell: bash
      run: npm install @actions/core @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v7
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          coredemo.setOutput('id_token', id_token)
    - name: Ensure ~/.kube directory exists
      shell: bash
      run: mkdir -p ~/.kube
    - name: Write ~/.kube/config
      shell: bash
      run: |      
          cat << EOF > ~/.kube/config
          apiVersion: v1
          kind: Config
          clusters:
              - cluster:
                  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUXpQb0ZXS1ArSUV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBME1UQXhOREEwTXpCYUZ3MHpOREEwTURneE5EQTVNekJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUQwTGdXSnd2ZDNuNGNudzlkQWdlQ2dWb2ZuMkd5Q2NTZ3UyYUlCQXhBRDk4ZkhXWE8vaDRscWY1eDEKZ1hHejdVZ3VXOE9oeXNwcDF0d09kUjdqNVJuS0FyaHlmbE41RWx0YUpnMFRTc3Nqa2wvUzNGL2MySDBoRFNYYwpScEhvRy9CTElPaWtyWDVxRFN5d3Qxa1lucWM1MWV4SzFGc1JNY3MrdDhYSjZoVnI2RlZ1L244YzhyeVB4NldwCkRwTGY5VWYrN1VvMXMwZ1hoVzV5RWFFYnhXOXZaRnEvZE5BanZEWW52TUhRNnAyaE84OW8vRmNmZzFRMkkrMWIKUGtlV2sxZEh6WVZvZi9GdzJUOEtiZTlpdWxuK1lCMEFRVlBTTmVHN2RKWGI0YnVzRS92OFRQZVdIcnJ3WmpiOQo2VkUwTTI2TXVNQWRQQlFKN3FYSFA3YWxaa1NIQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSNnMwb3VmckVza21pWHFCaVVjWDJmb2JXMU1EQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0NiYy9qaktsbgpGRittQ0dSbXRFWGNUV29ybHNnZ2NEVnMzSGN6bDJkMFdLLzY2WjBHTHhVaEZhSEZLRXVXbHdBZ0xpQyszek9iClVCNXpyKzJJL2lCYVdkczJBenBrUGo0TElvTWxsUlpTb3FwRDRJaWxUbHNKbDVMUXNQZHpwWVNnZHJVTC9TM2MKYURTWmh6VUlUbENmd1VBNHVxcitYWVBtS20vZUowWTJKbDVDMU03MGR5cy9WZGRiUG1tVlYyc292cGhLMzhZZAoxOFUyVW9TTFp1MEZnc0VJSXNaRjhjOFVqOTJGZ3NkSGdPcTNJSzZGaExLSE1FMXczYlRZNmRLS2ZBSlhEKzFFCk11VnFiM3NCQ2lmU2ZOVk5lS1o1MmQvWkQ5RHN6RnVBcWF4aEZFMnpJbUEwV1dwc0RKcXJ6NG5kWnJ2cXNxbU8KNzlVNE9WQi9JM1lwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                  server: https://bandit.shutthegoatup.com:6443
                name: bandit
              - cluster:
                  certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYUdld2tKblEwNkl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMk1USXlNVEUzTlRsYUZ3MHpOREEyTVRBeU1USXlOVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNoeEVsSnFrcFJUQTBUZXVRK0dyOFU5UDZoYy91eC9uY09XT0xuSUlUdXZJYVVtTjhSRjArQ25YcGwKNTI0M0JqM1A0blpBMDd6UmJlZm1VcUdVcU5ubUJaSWtMeURyQlllQ0hGRzRpem1EdW9taHZwNW4zQ1JWVkdTQgpjTjZlOTczVUZvalRHVWhnbzJOdU9abTBNMUc2VVQzK2t5N251MjRhVnVYSU1Dd05Tb1pOVHdIYU4xek5teTNZCnBZNC9IeFVTUXRIdmtSckZGVUlWc0pKOGVhMjZ5NGoySWgrbVRGWDJTUmZjeWJCNm56UTAya1hqNHMwSmRCekwKWDMwcmZqbGNVclNPQ3k4aDdQOWQvUlpGcDNnZktHNEl2eTA5a0pVNkFJZDR2NU5vTlBpQXZjZFRhU3VxQmlZMgpxOU52cWJtdkQ2ZzFaeFQ4UTB4VGhheW53ZXIvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRTDBVa0hHOExuc3c3a2ZjNlN2cFdGQklRb2lqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ1lEK05rd1FGNgp4NXFmSUhPZ3ZBTnhqU09iYlBwd25SSUxUeUJZWWRZeTZ3UHdKOTVocWkyYk1EclpFU0lhdWtBZVZJMnBITHk1CjdKcGZ4aVNYeE02MVdQSDk1MGxldDVpYlRjRloyY2lPWjlMbDRReE0zRDdBdnJlblZkQmFFcXgveUFrZDlVcWgKd3U5VkFyVWZDeGQxL3k1dlZwc05Vek5KY3JjNk45VnFFNy9TTUp1MzNuVWlnWFJmTk12RG1kR3RGUjFRUUFNQQpwc3hTWkJzeW1ITEJ3TDFVOEtPZktQSEUvbkZXaU9vbTNYOW8yNVRPa2R4L3BCQXROZE9KQXlkWGRqWmJPUGQ4CkoyUDBPckhQb3VVYkdVWWRYdlV1dFpZTmFQYUx3aWJwdS9ycWRWeU1uT2dXQkVrL0tVUVMySmc0VnRLQUNIWmEKNU5XS245VHZZZVdMCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
                  server: https://ghost.shutthegoatup.com:6443
                name: ghost
          contexts:
          - context:
              cluster: bandit
              user: gha
            name: bandit
          - context:
              cluster: ghost
              user: gha
            name: ghost
          current-context: ${{ inputs.cluster }}
          users:
          - name: gha
            user:
              token: ${{ steps.idtoken.outputs.id_token }}
          EOF