apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echoserver
  name: echoserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.10
        imagePullPolicy: Always
        name: echoserver
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 25m
            memory: 50Mi
