---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel
spec:
  instances: 3
  bootstrap:
    initdb:
      database: zitadel
  storage:
    storageClass: openebs-hostpath
    size: 10Gi
