---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: masterkey
  namespace: zitadel
spec:
  length: 32
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: masterkey
  namespace: zitadel
spec:
  refreshInterval: "30m"
  target:
    name: masterkey
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: masterkey
    rewrite:
    - regexp:
        source: "password"
        target: "masterkey"

---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: zitadel-humanuser
  namespace: zitadel
spec:
  length: 32
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zitadel-humanuser
  namespace: zitadel
spec:
  refreshInterval: "30m"
  target:
    name: zitadel-humanuser
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: zitadel-humanuser
