---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: masterkey
  namespace: zitadel
spec:
  length: 32
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: masterkey
  namespace: zitadel
spec:
  refreshInterval: "30m"
  target:
    template:
    name: masterkey
      engineVersion: v2
      data:
        masterkey: "{{ .masterkey.password }}"   
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: masterkey
