---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: masterkey
spec:
  length: 32
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: masterkey
spec:
  refreshInterval: "30m"
  target:
    name: masterkey
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: masterkey
---
