apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.crds.yaml

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    namespace: cert-manager
    includeCRDs: false
