apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

replacements:
- source:
    kind: ConfigMap
    name: platform-config
    namespace: kube-system
    fieldPath: data.server_name    
  targets:
  - select:
      kind: Ingress
      name: httpbin
      namespace: httpbin
    fieldPaths:
    - data.spec.rules.0.host
    options:
      delimiter: "."
      index: 1
