---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: example-kcpg
spec:
  instances: 3
  bootstrap:
    initdb:
      database: keycloak
  storage:
    storageClass: openebs-hostpath
    size: 10Gi
