apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: my-realm-kc
spec:
  keycloakCRName: example-kc
  realm:
    id: shuthegoatup
    realm: shuthegoatup
    displayName: Shut The Goat Up
    enabled: true