---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: vault
  name: vault-config-manager
rules:
- apiGroups: [""] 
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "update", create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: vault
  name: vault-config-manager
subjects:
- kind: ServiceAccount
  name: vault-config-manager 
  namespace: vault
- kind: ServiceAccount
  name: vault
  namespace: vault
roleRef:
  kind: Role 
  name: vault-config-manager
  apiGroup: rbac.authorization.k8s.io