apiVersion: v1
kind: Secret
metadata:
  name: vault-config-manager
  namespace: vault
stringData:
  vault-configure.yaml: |
    auth:
      - type: jwt
        config:
          bound_issuer: "https://token.actions.githubusercontent.com"            
          oidc_discovery_url: "https://token.actions.githubusercontent.com"
          default_role: robot 
        roles:
        - name: robot
          role_type: jwt
          user_claim: "actor"
          bound_claims_type: "glob"
          bound_claims: 
            repository: "shutthegoatup/*"
          policies: superadmin 
      - type: kubernetes
        config:
          kubernetes_host: https://kubernetes.default.svc.cluster.local
        roles:
          - name: robot
            bound_service_account_names: "*"
            bound_service_account_namespaces: "*"
            policies: superadmin
            ttl: 1h
            audience: https://s3.eu-west-2.amazonaws.com/ghost-k8s-oidc

    policies:
      - name: superadmin
        rules: path "*" {
                capabilities = ["create", "read", "update", "delete", "list"]
              }

    secrets:
      - type: kv
        path: kvv2
        description: "KV Version 2 secret engine mount"
        options:
          version: 2

    audit:
      - type: file
        description: "File based audit logging device"
        options:
          file_path: /dev/stdout