apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-image-store
  namespace: immich
spec:
  storageClassName: openebs-zfspv-largefiles
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Ti