---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-tls
  namespace: ingress-nginx
spec:
  dnsNames:
    - "*.shutthegoatup.com"
    - "*.millie.shutthegoatup.com"
    - "*.bandit.shutthegoatup.com"
    - "*.ghost.shutthegoatup.com"
    - "*.positron.uk"
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer