apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create the required namespaces
namespace: arc-systems

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  # ARC Controller Chart
  - name: arc-controller-renderapp
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    #chart: gha-runner-scale-set-controller
    releaseName: arc-controller-renderapp
    namespace: arc-systems
    includeCRDs: true

  # ARC Runner Scale Set Chart
  - name: arc-runner-renderapp
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    #chart: gha-runner-scale-set
    releaseName: arc-runner-set
    namespace: arc-runners
    valuesInline:
      githubConfigUrl: "https://github.com/renderappio/*"
      githubConfigSecret: github-app-renderapp
      maxRunners: 20
      minRunners: 5
      containerMode:
        type: "dind"
        kubernetesModeWorkVolumeClaim:
          accessModes: ["ReadWriteOnce"]
          storageClassName: "openebs-zfspv"
          resources:
            requests:
              storage: 5Gi


