apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Create the required namespaces
namespace: arc-systems

resources:
  - namespace.yaml
  - secrets.yaml

helmCharts:
  # ARC Controller Chart
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    releaseName: arc-controller-renderapp
    namespace: arc-systems
    includeCRDs: true
    valuesInline:
      serviceAccount:
        create: true
        name: arc-controller-renderapp
      template:
        spec:
          serviceAccountName: arc-controller-renderapp
          containers:
            env: 
            - name: KUBE_IN_CLUSTER_CONFIG
              value: "true"
    
  # ARC Runner Scale Set Chart
  - name: gha-runner-scale-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    releaseName: arc-runner-set
    namespace: arc-systems
    valuesFile: arc-runner-values.yaml


