---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-renderapp
  namespace: arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore 
  target:
    name: github-app-renderapp
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: /kvv2/github/renderapp
