---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app-renderapp
  namespace: arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore 
  target:
    name: github-app-renderapp
    creationPolicy: Owner
    template:
      type: Opaque
  dataFrom:
    - extract:
        key: /kvv2/github/renderapp
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-renderapp
  namespace: arc-systems
type: Opaque
data:
  # GitHub App ID (must be base64 encoded)
  # Replace with: echo -n "YOUR_APP_ID" | base64
  github_app_id: "MTIzNDU2"  # Example: 123456
  
  # GitHub App Installation ID (must be base64 encoded)
  # Replace with: echo -n "YOUR_INSTALLATION_ID" | base64
  github_app_installation_id: "NjU0MzIx"  # Example: 654321
  
  # GitHub App Private Key (must be base64 encoded)
  # Replace with: cat private-key.pem | base64 -w 0
  github_app_private_key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpZT1VSX1BSSVZBVEVFX0tFWV9IRVJFCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
