---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  name: httpbin
  namespace: httpbin
spec:
  ingressClassName: nginx
  rules:
  - host: httpbin.bandit.shutthegoatup.com
    http:
      paths:
      - backend:
          service:
            name: httpbin
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific