---
name: "services"

on:
  pull_request:
    branches:
    - main

jobs:
  terraform:
    if: github.event.pull_request.merged != true
    name: "Terraform Plan"    
    runs-on: gha-runner-scale-set
    container: hashicorp/terraform:latest
    defaults:
      run:
        working-directory: terraform/06_services
    steps:
      - name: Checkout
        uses: actions/checkout@v3          
      - run: terraform init
      - id: plan
        run: terraform plan -no-color

