---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv-default
  annotations:
    storageclass.kubernetes.io/is-default-class: true
allowVolumeExpansion: true
parameters:
  recordsize: "128k"
  compression: "lz4"
  dedup: "on"
  fstype: "zfs"
  poolname: "data"
  thinprovision: "yes"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - millie
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv-pgsql
allowVolumeExpansion: true
parameters:
  recordsize: "8k"
  compression: "lz4"
  dedup: "off"
  fstype: "zfs"
  poolname: "data"
  thinprovision: "yes"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - millie
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-zfspv-largefiles
allowVolumeExpansion: true
parameters:
  recordsize: "1M"
  compression: "lz4"
  dedup: "on"
  fstype: "zfs"
  poolname: "data"
  thinprovision: "yes"
provisioner: zfs.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: kubernetes.io/hostname
    values:
      - millie
